import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Frame from "@/components/sections/Frame";
import Footer from "@/components/sections/Footer";
import {ReactLenis} from './utils/lenis.js'

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Malak Photography",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* <ReactLenis> */}
        <body className={`${inter.className} antialiased`}>
          <Frame />
          <main className="bg-black z-5   relative w-full pb-26">
            <div className="m-28 ">{children}</div>
          </main>
          <Footer />
        </body>
      {/* </ReactLenis> */}
    </html>
  );
}
