import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Frame from "@/components/sections/Frame";
import Footer from "@/components/sections/Footer";

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Malak Photography",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
      >
        <Frame/>

        <div className="bg-black z-5  relative w-full pb-26">
          <div className="m-28 flex flex-col gap-40">{children}</div>
          </div>
        <Footer/>
      </body>
    </html>
  );
}
